### ISSUE TITLE
Doesn't Kill my device enough

### ISSUE THREAD

**Issue by Apph3x** [arcticsn0w/killios#1]
WHY OH WHY DOESN'T IT MESS WITH MAC ADDRESSES AND WIFI THINGS AS WELL. WHY DOESN'T IT SHOW OUTPUT SO IT SCARES KIDDIES ?? :P jks, but plz do the output...

**Comment by arcticsn0w** [comment]
Fixed in 1.2

**Comment by Apph3x** [comment]
YAYAAYAYAYAY
