### ISSUE TITLE
Repo won't install: http://arcticsn0w.tk/

### ISSUE THREAD

**Issue by hardfuckingcore** [arcticsn0w/killios#10]
I don't want to install killios but when I try to download the repo it won't download and I get some error and I'm unable to view any tweaks. Tried this on my iPod touch 5th generation jailbroken on iOS 7.1.2 and an iPhone 5S on iOS 8.1.2. I just want to view the package and take a screenshot of it but not install it cuz my phone and iPod are worth a lot of money.

**Comment by arcticsn0w** [comment]
1. KilliOS is no longer on my Cydia repository, and is no longer available for downloads.

2. My Cydia repository is http://arcticsn0w.github.io
